[package]
name = "snake_game"
version = "0.5.0"
edition = "2021"

[dependencies]
minifb = "0.21.0"
image = "0.24.6"
winit = "0.27"
rodio = "0.17.1"
rand = "0.9.1"
log = "0.4.27"

[[bin]]
name = "snake_game"
path = "src/main.rs"

