[package]
name = "space_wurm"
version = "0.5.0"
edition = "2021"

[dependencies]
minifb = "0.28.0"
image = "0.25.6"
winit = "0.27.0"
rodio = "0.20.1"
rand = "0.9.1"

[[bin]]
name = "space_wurm"
path = "src/main.rs"

